version: 1.0.{build}
branches:
  only:
    - master

shallow_clone: false
skip_tags: true
clone_depth: 1

image: Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: false

build_script:
  - cmd: git submodule update --init --recursive
  - cmd: msbuild Vulkano.sln
